# Generated by Django 5.2.13 on 2026-04-26 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cause', models.TextField()),
                ('symptoms', models.TextField()),
                ('remedy', models.TextField()),
                ('prevention', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=10)),
                ('affected_parts', models.CharField(blank=True, max_length=200)),
                ('disease_image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='plants.plant')),
            ],
            options={
                'unique_together': {('plant', 'name')},
            },
        ),
    ]
