# Generated by Django 5.2.13 on 2026-04-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='detections/uploads/')),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='detections/gradcam/')),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('low_confidence', 'Low Confidence'), ('failed', 'Failed')], default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='diseases.disease')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='plants.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
