# Generated by Django 5.2.16 on 2026-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_alter_detection_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='preprocessing_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detection',
            name='stage1_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detection',
            name='stage1_model',
            field=models.CharField(default='EfficientNetB0', max_length=30),
        ),
        migrations.AddField(
            model_name='detection',
            name='stage2_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detection',
            name='stage2_model',
            field=models.CharField(default='MobileNetV2', max_length=30),
        ),
        migrations.AddField(
            model_name='detection',
            name='total_latency_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
